CREATE TABLE IF NOT EXISTS `b_your_module_example` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,
    `DATE_CREATE` DATETIME NOT NULL,
    `ACTIVE` CHAR(1) NOT NULL DEFAULT 'Y',
    PRIMARY KEY (`ID`),
    INDEX `IX_ACTIVE` (`ACTIVE`)
);