version: "3.8"

services:
  php:
    image: php:8.1-cli
    container_name: bitrix_test_php
    working_dir: /app
    volumes:
      - ./:/app
    command: tail -f /dev/null

  db:
    image: mariadb:10.6
    container_name: bitrix_test_db
    environment:
      MYSQL_ROOT_PASSWORD: bitrix
      MYSQL_DATABASE: sitemanager
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: bitrix
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
